spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver"
  cloud:
    config:
      uri: http://localhost:8888

# Configure Tomcat
server:
  port: 9001
  tomcat:
    connection-timeout: 2
    keep-alive-timeout: 15
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Welcome to the local book catalog!
